version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/"
  target-branch: "zengin_code"
  schedule:
    interval: daily
  allow:
    - dependency-name: "zengin_code"
  open-pull-requests-limit: 5